# -*- coding: utf-8 -*-
"""analisis-actas-jos-jeri-conectado-a-chatgtp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/ramos731-ui/2016aacad8208d4cd3ae2fcde7c1bd15/analisis-actas-jos-jeri-conectado-a-chatgtp.ipynb
"""

#LIBRERIAS Y PREPARACIÓN
!pip install pymupdf pandas openai matplotlib seaborn openpyxl
import os
import fitz
import pandas as pd
import json
from openai import OpenAI
from google.colab import files
import collections
import re

client = OpenAI(api_key="AQUÍ PEGAR TU API_KEY") 
MODELO_ELEGIDO = "gpt-4o"

## APROBACIÓN DEL MODELO Y CARGA
def validar_y_subir():
    try:
        client.models.retrieve(MODELO_ELEGIDO)
        print(f"✅ API Aprobada. Analizando periodo Jerí (2025-2026).")
    except Exception as e:
        print(f"❌ Error de API: {e}")
        return None

    print("\n📂 CARGA MASIVA: Selecciona las 12 actas de consejo de ministros:")
    subida = files.upload()
    return list(subida.keys()) if subida else None

nombres_archivos = validar_y_subir()

###TEXT MINING (FRECUENCIA DE PALABRAS Y EXTRACCIÓN)
def procesar_minería_texto(nombre_archivo):
    texto = ""
    with fitz.open(nombre_archivo) as doc:
        for pagina in doc:
            texto += pagina.get_text()

    # Limpieza para encontrar palabras clave frecuentes
    texto_limpio = " ".join(texto.split())
    palabras = re.findall(r'\w+', texto_limpio.lower())

    # Filtro de palabras comunes (stop words simples)
    stop_words = {'el', 'la', 'de', 'que', 'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por', 'un', 'con', 'no', 'una', 'su', 'para', 'es', 'al', 'lo', 'como', 'más', 'pero', 'sus', 'le', 'ya', 'o', 'fue', 'este', 'ha', 'si', 'porque', 'esta', 'son', 'entre', 'está', 'cuando', 'muy', 'sin', 'sobre', 'ser', 'tiene', 'también', 'me', 'hasta', 'hay', 'donde', 'han', 'quien', 'están', 'estado', 'ministro', 'consejo', 'acta', 'sesión', 'aprobación'}

    filtradas = [p for p in palabras if p not in stop_words and len(p) > 3]
    frecuencia = collections.Counter(filtradas).most_common(5)
    palabras_top = ", ".join([f"{p[0]} ({p[1]})" for p in frecuencia])

    return texto_limpio, palabras_top

#ANALISIS IA CON CONTEXTO DE PALABRAS
def analizar_acta(texto, palabras_top, nombre):
    # Contexto histórico para la IA
    contexto_prensa = """
    Contexto mediático (Oct 2025 - Feb 2026):
    - Oct 2025: Vacancia de Boluarte y asunción de José Jerí.
    - Nov-Dic 2025: Crisis de extorsiones y paros de transportistas.
    - Ene 2026: Escándalo 'Chifagate' (reuniones secretas con empresarios chinos).
    - Feb 2026: Denuncias por contrataciones irregulares y censura de Jerí.
    - General: Preparación para Elecciones de Abril 2026.
    """

    prompt = f"""
    Eres un analista político senior. Analiza esta acta del Consejo de Ministros de la gestión José Jerí.

    CONTEXTO DE PRENSA DEL PERIODO: {contexto_prensa}
    PALABRAS MÁS FRECUENTES EN ESTE DOCUMENTO: {palabras_top}

    Responde en JSON con estas claves exactas:
    {{
        "fecha_acta": "YYYY-MM-DD",
        "temas_tocados": "Resumen de los puntos principales de la agenda",
        "palabras_clave_minería": "Copia aquí las palabras más frecuentes enviadas",
        "contexto_noticioso_externo": "A partir de la fecha del acta, describe qué temas dominaban la prensa nacional en ese momento específico.",
        "analisis_discrepancia": "Breve nota sobre si el acta ignora o aborda los problemas críticos que la prensa reportaba en esa fecha."
    }}

    TEXTO DEL ACTA: {texto[:100000]}
    """

    response = client.chat.completions.create(
        model=MODELO_ELEGIDO,
        messages=[{"role": "user", "content": prompt}],
        response_format={ "type": "json_object" }
    )
    return json.loads(response.choices[0].message.content)

##GENERACIÓN DE EXCEL ORDENADO
if nombres_archivos:
    resultados = []
    for nombre in nombres_archivos:
        texto, top_words = procesar_minería_texto(nombre)
        data = analizar_acta(texto, top_words, nombre)
        resultados.append(data)

    # Crear DataFrame
    df = pd.DataFrame(resultados)

    # Convertir fecha y ordenar de más antiguo a más nuevo
    df['fecha_acta'] = pd.to_datetime(df['fecha_acta'])
    df = df.sort_values(by='fecha_acta', ascending=True)

    # Guardar Excel
    nombre_excel = "Analisis_Jerí_TextMining.xlsx"
    df.to_excel(nombre_excel, index=False)

    print(f"\n📊 Análisis completado. Se han procesado {len(df)} actas.")
    print(f"✅ Archivo '{nombre_excel}' listo para descargar.")
